version: 2

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/irfandi/celebrum-ai-go
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  funlen:
    lines: 100
    statements: 50
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID", "URL", "HTTP", "API", "DB", "SQL", "JSON", "YAML", "CCXT", "UUID", "OHLCV"]

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - misspell
    - revive
    - unconvert
    - unparam
    - gosec
    - gocritic
    - copyloopvar  # replaces exportloopref

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
    - path: internal/testutil/
      linters:
        - errcheck
        - gosec
    - path: test/
      linters:
        - errcheck
        - gosec
        - gocyclo
        - funlen

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - node_modules
    - bin
    - build
    - .cache
  exclude-files:
    - ".*\\.pb\\.go$"

run:
  timeout: 5m
  tests: true
