# Celebrum AI Configuration Template
# Copy this file to config.local.yaml and modify as needed

# Application environment (development, staging, production)
environment: development

# Logging configuration
logging:
  level: info # debug, info, warn, error
  format: json # json, text
  output: stdout # stdout, file
  file_path: logs/app.log

# Server configuration
server:
  port: 8080
  host: 0.0.0.0
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "https://celebrum-ai.com"

# Database configuration
database:
  # For local development - SECURITY: Set DATABASE_PASSWORD environment variable
  host: localhost
  port: 5432
  user: postgres
  password: "" # SECURITY: Use DATABASE_PASSWORD environment variable instead
  dbname: celebrum_ai
  sslmode: disable

  # For Digital Ocean managed database (use DATABASE_URL environment variable)
  # database_url: "postgres://username:password@host:port/dbname?sslmode=require"

  # Connection pool settings (optimized for cloud deployment)
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300s
  conn_max_idle_time: 60s

# Redis configuration
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s

# CCXT Service configuration
ccxt:
  service_url: http://localhost:3001
  timeout: 30
  retry_attempts: 3
  retry_delay: 1s
  rate_limit:
    requests_per_second: 10
    burst: 20

# Telegram Bot configuration
telegram:
  bot_token: ""
  webhook_url: ""
  webhook_secret: ""
  timeout: 30s

# Market Data configuration
market_data:
  collection_interval: 5m # Collect data every 5 minutes (optimized for efficiency)
  batch_size: 500
  max_retries: 3
  timeout: 15s
  exchanges:
    - binance
    - coinbase
    - kraken
    - bitfinex
    - huobi

# Data Cleanup configuration
cleanup:
  # Smart cleanup strategy - maintains 24h buffer while cleaning old data
  market_data:
    retention_hours: 36 # Keep 36 hours of market data
    deletion_hours: 12 # Delete oldest 12 hours when cleaning (keeps 24h buffer)
  funding_rates:
    retention_hours: 36 # Keep 36 hours of funding rate data
    deletion_hours: 12 # Delete oldest 12 hours when cleaning
  arbitrage_opportunities:
    retention_hours: 72 # Keep 72 hours of arbitrage opportunities
  interval_minutes: 60 # Run cleanup every 60 minutes
  enable_smart_cleanup: true # Use smart cleanup strategy

# Historical Data Backfill configuration
backfill:
  enabled: true # Enable backfill on startup
  backfill_hours: 6 # Collect 6 hours of historical data
  min_data_threshold_hours: 4 # Trigger backfill if less than 4h of data available
  batch_size: 5 # Process 5 symbols at a time
  delay_between_batches: 500 # Delay in milliseconds between symbol processing

# Arbitrage configuration
arbitrage:
  min_profit_threshold: 0.5 # Minimum profit percentage
  max_trade_amount: 1000.0 # Maximum trade amount in USD
  check_interval: 2m # Check for opportunities every 2 minutes
  enabled_pairs:
    - BTC/USDT
    - ETH/USDT
    - BNB/USDT
    - ADA/USDT

# Technical Analysis configuration
technical_analysis:
  indicators:
    - RSI
    - MACD
    - SMA
    - EMA
    - BOLLINGER_BANDS
  timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
  calculation_interval: 60s

# Security configuration
security:
  jwt_secret: "" # SECURITY: Use JWT_SECRET environment variable - never hardcode secrets
  jwt_expiry: 24h
  bcrypt_cost: 12
  rate_limit:
    requests_per_minute: 100
    burst: 200

# Monitoring configuration
monitoring:
  metrics_enabled: true
  metrics_port: 9090
  health_check_interval: 30s
  prometheus:
    enabled: true
    path: /metrics

# Feature flags
features:
  telegram_bot: true
  web_interface: true
  api_v1: true
  real_trading: false # Set to true only in production with proper safeguards
  paper_trading: true

# External APIs
external_apis:
  coingecko:
    base_url: https://api.coingecko.com/api/v3
    timeout: 10s
    rate_limit: 50 # requests per minute
  coinmarketcap:
    base_url: https://pro-api.coinmarketcap.com/v1
    api_key: ""
    timeout: 10s
    rate_limit: 333 # requests per day for free tier
