# Docker Compose Override for Local Development
# This file is automatically merged with docker-compose.yml for local development
# It overrides settings specifically for development environment

services:
  postgres:
    ports:
      - "127.0.0.1:5432:5432"  # Expose PostgreSQL on standard port for local development
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: celebrum_ai

  redis:
    ports:
      - "127.0.0.1:6379:6379"  # Expose Redis on standard port for local development

  ccxt-service:
    ports:
      - "127.0.0.1:3001:3001"  # Expose CCXT service on standard port
    environment:
      NODE_ENV: development
      PORT: 3001
    volumes:
      - ./ccxt-service:/app:ro  # Read-only mount for development
    restart: unless-stopped

  app:
    ports:
      - "127.0.0.1:8080:8080"  # Expose main app on standard port
    environment:
      ENVIRONMENT: development
      CONFIG_PATH: /app/configs/config.local.yml
      CCXT_SERVICE_URL: http://ccxt-service:3001
    volumes:
      - ./configs:/app/configs:ro
      - ./logs:/app/logs
      - .:/app:ro  # Mount source code for development
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ccxt-service:
        condition: service_healthy

  # Add development tools
  adminer:
    image: adminer:latest
    container_name: celebrum-adminer
    ports:
      - "127.0.0.1:8081:8080"  # Database admin interface
    depends_on:
      - postgres
    profiles:
      - dev-tools

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: celebrum-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "127.0.0.1:8082:8081"  # Redis admin interface
    depends_on:
      - redis
    profiles:
      - dev-tools