name: Security Report
description: Report a security vulnerability (Please read SECURITY.md first)
title: "[SECURITY] "
labels: ["security", "critical"]
assignees: ["irfandi"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For security vulnerabilities, please **DO NOT** create public issues.
        
        Instead, please:
        1. **Email**: security@celebrum-ai.com
        2. **Security Advisory**: [Create private security advisory](https://github.com/irfndi/celebrum-ai-go/security/advisories/new)
        
        This template is for **general security concerns** or **after** a vulnerability has been responsibly disclosed.

  - type: checkboxes
    id: checklist
    attributes:
      label: Security Checklist
      options:
        - label: I have read the [SECURITY.md](SECURITY.md) policy
          required: true
        - label: This is NOT a zero-day vulnerability (already responsibly disclosed)
          required: true
        - label: I understand this will be handled with high priority
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How critical is this security concern?
      options:
        - Critical (Remote code execution, data breach)
        - High (Authentication bypass, privilege escalation)
        - Medium (Information disclosure, DoS)
        - Low (Minor security improvements)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Concern Description
      description: Describe the security issue or concern
      placeholder: Describe the security concern...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could be the impact if exploited?
      placeholder: Describe the potential security impact...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if applicable)
      description: How can this security issue be reproduced?
      placeholder: |
        1. [Step 1]
        2. [Step 2]
        3. [Step 3]
        4. [Security issue occurs]

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Any suggestions for fixing or mitigating this issue?
      placeholder: Suggested fixes or mitigations...

  - type: textarea
    id: evidence
    attributes:
      label: Evidence/Proof of Concept
      description: Any evidence, logs, or proof of concept
      placeholder: |
        ```
        Logs, screenshots, or code examples
        ```
      render: shell

  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: How can we contact you for follow-up (optional)
      placeholder: Email or preferred contact method