// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: ccxt_service.proto

package ccxt

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTickerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickerRequest) Reset() {
	*x = GetTickerRequest{}
	mi := &file_ccxt_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerRequest) ProtoMessage() {}

func (x *GetTickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerRequest.ProtoReflect.Descriptor instead.
func (*GetTickerRequest) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetTickerRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetTickerRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetTickerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Ticker        *TickerData            `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickerResponse) Reset() {
	*x = GetTickerResponse{}
	mi := &file_ccxt_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerResponse) ProtoMessage() {}

func (x *GetTickerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerResponse.ProtoReflect.Descriptor instead.
func (*GetTickerResponse) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTickerResponse) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetTickerResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTickerResponse) GetTicker() *TickerData {
	if x != nil {
		return x.Ticker
	}
	return nil
}

func (x *GetTickerResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetTickerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TickerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Last          string                 `protobuf:"bytes,1,opt,name=last,proto3" json:"last,omitempty"`
	High          string                 `protobuf:"bytes,2,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`
	Bid           string                 `protobuf:"bytes,4,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask           string                 `protobuf:"bytes,5,opt,name=ask,proto3" json:"ask,omitempty"`
	BaseVolume    string                 `protobuf:"bytes,6,opt,name=base_volume,json=baseVolume,proto3" json:"base_volume,omitempty"`
	QuoteVolume   string                 `protobuf:"bytes,7,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickerData) Reset() {
	*x = TickerData{}
	mi := &file_ccxt_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerData) ProtoMessage() {}

func (x *TickerData) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerData.ProtoReflect.Descriptor instead.
func (*TickerData) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{2}
}

func (x *TickerData) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

func (x *TickerData) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *TickerData) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *TickerData) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *TickerData) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

func (x *TickerData) GetBaseVolume() string {
	if x != nil {
		return x.BaseVolume
	}
	return ""
}

func (x *TickerData) GetQuoteVolume() string {
	if x != nil {
		return x.QuoteVolume
	}
	return ""
}

type GetTickersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchanges     []string               `protobuf:"bytes,1,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	Symbols       []string               `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickersRequest) Reset() {
	*x = GetTickersRequest{}
	mi := &file_ccxt_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickersRequest) ProtoMessage() {}

func (x *GetTickersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickersRequest.ProtoReflect.Descriptor instead.
func (*GetTickersRequest) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTickersRequest) GetExchanges() []string {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

func (x *GetTickersRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type ExchangeTicker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Ticker        *TickerData            `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeTicker) Reset() {
	*x = ExchangeTicker{}
	mi := &file_ccxt_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeTicker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeTicker) ProtoMessage() {}

func (x *ExchangeTicker) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeTicker.ProtoReflect.Descriptor instead.
func (*ExchangeTicker) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeTicker) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *ExchangeTicker) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ExchangeTicker) GetTicker() *TickerData {
	if x != nil {
		return x.Ticker
	}
	return nil
}

func (x *ExchangeTicker) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExchangeTicker) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetTickersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickers       []*ExchangeTicker      `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickersResponse) Reset() {
	*x = GetTickersResponse{}
	mi := &file_ccxt_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickersResponse) ProtoMessage() {}

func (x *GetTickersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickersResponse.ProtoReflect.Descriptor instead.
func (*GetTickersResponse) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTickersResponse) GetTickers() []*ExchangeTicker {
	if x != nil {
		return x.Tickers
	}
	return nil
}

func (x *GetTickersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketsRequest) Reset() {
	*x = GetMarketsRequest{}
	mi := &file_ccxt_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketsRequest) ProtoMessage() {}

func (x *GetMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketsRequest.ProtoReflect.Descriptor instead.
func (*GetMarketsRequest) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetMarketsRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

type GetMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbols       []string               `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketsResponse) Reset() {
	*x = GetMarketsResponse{}
	mi := &file_ccxt_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketsResponse) ProtoMessage() {}

func (x *GetMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketsResponse.ProtoReflect.Descriptor instead.
func (*GetMarketsResponse) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetMarketsResponse) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetMarketsResponse) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *GetMarketsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetMarketsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetFundingRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbols       []string               `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFundingRatesRequest) Reset() {
	*x = GetFundingRatesRequest{}
	mi := &file_ccxt_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFundingRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundingRatesRequest) ProtoMessage() {}

func (x *GetFundingRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundingRatesRequest.ProtoReflect.Descriptor instead.
func (*GetFundingRatesRequest) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetFundingRatesRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetFundingRatesRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type GetFundingRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Rates         []*FundingRate         `protobuf:"bytes,2,rep,name=rates,proto3" json:"rates,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFundingRatesResponse) Reset() {
	*x = GetFundingRatesResponse{}
	mi := &file_ccxt_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFundingRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundingRatesResponse) ProtoMessage() {}

func (x *GetFundingRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundingRatesResponse.ProtoReflect.Descriptor instead.
func (*GetFundingRatesResponse) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetFundingRatesResponse) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetFundingRatesResponse) GetRates() []*FundingRate {
	if x != nil {
		return x.Rates
	}
	return nil
}

func (x *GetFundingRatesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FundingRate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Symbol          string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	FundingRate     string                 `protobuf:"bytes,2,opt,name=funding_rate,json=fundingRate,proto3" json:"funding_rate,omitempty"`
	Timestamp       int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NextFundingTime int64                  `protobuf:"varint,4,opt,name=next_funding_time,json=nextFundingTime,proto3" json:"next_funding_time,omitempty"`
	MarkPrice       string                 `protobuf:"bytes,5,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	IndexPrice      string                 `protobuf:"bytes,6,opt,name=index_price,json=indexPrice,proto3" json:"index_price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FundingRate) Reset() {
	*x = FundingRate{}
	mi := &file_ccxt_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingRate) ProtoMessage() {}

func (x *FundingRate) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingRate.ProtoReflect.Descriptor instead.
func (*FundingRate) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{10}
}

func (x *FundingRate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FundingRate) GetFundingRate() string {
	if x != nil {
		return x.FundingRate
	}
	return ""
}

func (x *FundingRate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FundingRate) GetNextFundingTime() int64 {
	if x != nil {
		return x.NextFundingTime
	}
	return 0
}

func (x *FundingRate) GetMarkPrice() string {
	if x != nil {
		return x.MarkPrice
	}
	return ""
}

func (x *FundingRate) GetIndexPrice() string {
	if x != nil {
		return x.IndexPrice
	}
	return ""
}

type GetOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookRequest) Reset() {
	*x = GetOrderBookRequest{}
	mi := &file_ccxt_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookRequest) ProtoMessage() {}

func (x *GetOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderBookRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetOrderBookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderBookRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetOrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Orderbook     *OrderBook             `protobuf:"bytes,3,opt,name=orderbook,proto3" json:"orderbook,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookResponse) Reset() {
	*x = GetOrderBookResponse{}
	mi := &file_ccxt_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookResponse) ProtoMessage() {}

func (x *GetOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookResponse.ProtoReflect.Descriptor instead.
func (*GetOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderBookResponse) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetOrderBookResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderBookResponse) GetOrderbook() *OrderBook {
	if x != nil {
		return x.Orderbook
	}
	return nil
}

func (x *GetOrderBookResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetOrderBookResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OrderBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          []*PriceLevel          `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevel          `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce         int64                  `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBook) Reset() {
	*x = OrderBook{}
	mi := &file_ccxt_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBook) ProtoMessage() {}

func (x *OrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBook.ProtoReflect.Descriptor instead.
func (*OrderBook) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{13}
}

func (x *OrderBook) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderBook) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *OrderBook) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OrderBook) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_ccxt_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{14}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type GetTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradesRequest) Reset() {
	*x = GetTradesRequest{}
	mi := &file_ccxt_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradesRequest) ProtoMessage() {}

func (x *GetTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradesRequest.ProtoReflect.Descriptor instead.
func (*GetTradesRequest) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetTradesRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetTradesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTradesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Cost          string                 `protobuf:"bytes,7,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_ccxt_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{16}
}

func (x *Trade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trade) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Trade) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Trade) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Trade) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}

type GetTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,3,rep,name=trades,proto3" json:"trades,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradesResponse) Reset() {
	*x = GetTradesResponse{}
	mi := &file_ccxt_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradesResponse) ProtoMessage() {}

func (x *GetTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradesResponse.ProtoReflect.Descriptor instead.
func (*GetTradesResponse) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetTradesResponse) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetTradesResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *GetTradesResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetTradesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetOHLCVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timeframe     string                 `protobuf:"bytes,3,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOHLCVRequest) Reset() {
	*x = GetOHLCVRequest{}
	mi := &file_ccxt_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOHLCVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOHLCVRequest) ProtoMessage() {}

func (x *GetOHLCVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOHLCVRequest.ProtoReflect.Descriptor instead.
func (*GetOHLCVRequest) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetOHLCVRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetOHLCVRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOHLCVRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *GetOHLCVRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetOHLCVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timeframe     string                 `protobuf:"bytes,3,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Candles       []*OHLCV               `protobuf:"bytes,4,rep,name=candles,proto3" json:"candles,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOHLCVResponse) Reset() {
	*x = GetOHLCVResponse{}
	mi := &file_ccxt_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOHLCVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOHLCVResponse) ProtoMessage() {}

func (x *GetOHLCVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOHLCVResponse.ProtoReflect.Descriptor instead.
func (*GetOHLCVResponse) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetOHLCVResponse) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetOHLCVResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOHLCVResponse) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *GetOHLCVResponse) GetCandles() []*OHLCV {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *GetOHLCVResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetOHLCVResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OHLCV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Open          string                 `protobuf:"bytes,2,opt,name=open,proto3" json:"open,omitempty"`
	High          string                 `protobuf:"bytes,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         string                 `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        string                 `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OHLCV) Reset() {
	*x = OHLCV{}
	mi := &file_ccxt_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OHLCV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OHLCV) ProtoMessage() {}

func (x *OHLCV) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OHLCV.ProtoReflect.Descriptor instead.
func (*OHLCV) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{20}
}

func (x *OHLCV) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OHLCV) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *OHLCV) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *OHLCV) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *OHLCV) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *OHLCV) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

type GetExchangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangesRequest) Reset() {
	*x = GetExchangesRequest{}
	mi := &file_ccxt_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangesRequest) ProtoMessage() {}

func (x *GetExchangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangesRequest.ProtoReflect.Descriptor instead.
func (*GetExchangesRequest) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{21}
}

type GetExchangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchanges     []*ExchangeInfo        `protobuf:"bytes,1,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangesResponse) Reset() {
	*x = GetExchangesResponse{}
	mi := &file_ccxt_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangesResponse) ProtoMessage() {}

func (x *GetExchangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangesResponse.ProtoReflect.Descriptor instead.
func (*GetExchangesResponse) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetExchangesResponse) GetExchanges() []*ExchangeInfo {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

func (x *GetExchangesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExchangeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Countries     []string               `protobuf:"bytes,3,rep,name=countries,proto3" json:"countries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeInfo) Reset() {
	*x = ExchangeInfo{}
	mi := &file_ccxt_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeInfo) ProtoMessage() {}

func (x *ExchangeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeInfo.ProtoReflect.Descriptor instead.
func (*ExchangeInfo) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{23}
}

func (x *ExchangeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExchangeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExchangeInfo) GetCountries() []string {
	if x != nil {
		return x.Countries
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_ccxt_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{24}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_ccxt_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ccxt_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_ccxt_service_proto_rawDescGZIP(), []int{25}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_ccxt_service_proto protoreflect.FileDescriptor

const file_ccxt_service_proto_rawDesc = "" +
	"\n" +
	"\x12ccxt_service.proto\x12\x04ccxt\"F\n" +
	"\x10GetTickerRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\"\xa5\x01\n" +
	"\x11GetTickerResponse\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12(\n" +
	"\x06ticker\x18\x03 \x01(\v2\x10.ccxt.TickerDataR\x06ticker\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xae\x01\n" +
	"\n" +
	"TickerData\x12\x12\n" +
	"\x04last\x18\x01 \x01(\tR\x04last\x12\x12\n" +
	"\x04high\x18\x02 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x03 \x01(\tR\x03low\x12\x10\n" +
	"\x03bid\x18\x04 \x01(\tR\x03bid\x12\x10\n" +
	"\x03ask\x18\x05 \x01(\tR\x03ask\x12\x1f\n" +
	"\vbase_volume\x18\x06 \x01(\tR\n" +
	"baseVolume\x12!\n" +
	"\fquote_volume\x18\a \x01(\tR\vquoteVolume\"K\n" +
	"\x11GetTickersRequest\x12\x1c\n" +
	"\texchanges\x18\x01 \x03(\tR\texchanges\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbols\"\xa2\x01\n" +
	"\x0eExchangeTicker\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12(\n" +
	"\x06ticker\x18\x03 \x01(\v2\x10.ccxt.TickerDataR\x06ticker\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"Z\n" +
	"\x12GetTickersResponse\x12.\n" +
	"\atickers\x18\x01 \x03(\v2\x14.ccxt.ExchangeTickerR\atickers\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"/\n" +
	"\x11GetMarketsRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\"v\n" +
	"\x12GetMarketsResponse\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbols\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"N\n" +
	"\x16GetFundingRatesRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbols\"t\n" +
	"\x17GetFundingRatesResponse\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12'\n" +
	"\x05rates\x18\x02 \x03(\v2\x11.ccxt.FundingRateR\x05rates\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xd2\x01\n" +
	"\vFundingRate\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\ffunding_rate\x18\x02 \x01(\tR\vfundingRate\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12*\n" +
	"\x11next_funding_time\x18\x04 \x01(\x03R\x0fnextFundingTime\x12\x1d\n" +
	"\n" +
	"mark_price\x18\x05 \x01(\tR\tmarkPrice\x12\x1f\n" +
	"\vindex_price\x18\x06 \x01(\tR\n" +
	"indexPrice\"_\n" +
	"\x13GetOrderBookRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xad\x01\n" +
	"\x14GetOrderBookResponse\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12-\n" +
	"\torderbook\x18\x03 \x01(\v2\x0f.ccxt.OrderBookR\torderbook\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x8b\x01\n" +
	"\tOrderBook\x12$\n" +
	"\x04bids\x18\x01 \x03(\v2\x10.ccxt.PriceLevelR\x04bids\x12$\n" +
	"\x04asks\x18\x02 \x03(\v2\x10.ccxt.PriceLevelR\x04asks\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x03R\x05nonce\":\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"\\\n" +
	"\x10GetTradesRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xa3\x01\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x12\n" +
	"\x04cost\x18\a \x01(\tR\x04cost\"\xa0\x01\n" +
	"\x11GetTradesResponse\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12#\n" +
	"\x06trades\x18\x03 \x03(\v2\v.ccxt.TradeR\x06trades\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"y\n" +
	"\x0fGetOHLCVRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x03 \x01(\tR\ttimeframe\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xbf\x01\n" +
	"\x10GetOHLCVResponse\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x03 \x01(\tR\ttimeframe\x12%\n" +
	"\acandles\x18\x04 \x03(\v2\v.ccxt.OHLCVR\acandles\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x8d\x01\n" +
	"\x05OHLCV\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04open\x18\x02 \x01(\tR\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\tR\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\tR\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\tR\x06volume\"\x15\n" +
	"\x13GetExchangesRequest\"^\n" +
	"\x14GetExchangesResponse\x120\n" +
	"\texchanges\x18\x01 \x03(\v2\x12.ccxt.ExchangeInfoR\texchanges\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"P\n" +
	"\fExchangeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcountries\x18\x03 \x03(\tR\tcountries\"\x14\n" +
	"\x12HealthCheckRequest\"a\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice2\xe8\x04\n" +
	"\vCcxtService\x12<\n" +
	"\tGetTicker\x12\x16.ccxt.GetTickerRequest\x1a\x17.ccxt.GetTickerResponse\x12?\n" +
	"\n" +
	"GetMarkets\x12\x17.ccxt.GetMarketsRequest\x1a\x18.ccxt.GetMarketsResponse\x12N\n" +
	"\x0fGetFundingRates\x12\x1c.ccxt.GetFundingRatesRequest\x1a\x1d.ccxt.GetFundingRatesResponse\x12E\n" +
	"\fGetOrderBook\x12\x19.ccxt.GetOrderBookRequest\x1a\x1a.ccxt.GetOrderBookResponse\x129\n" +
	"\bGetOHLCV\x12\x15.ccxt.GetOHLCVRequest\x1a\x16.ccxt.GetOHLCVResponse\x12E\n" +
	"\fGetExchanges\x12\x19.ccxt.GetExchangesRequest\x1a\x1a.ccxt.GetExchangesResponse\x12?\n" +
	"\n" +
	"GetTickers\x12\x17.ccxt.GetTickersRequest\x1a\x18.ccxt.GetTickersResponse\x12<\n" +
	"\tGetTrades\x12\x16.ccxt.GetTradesRequest\x1a\x17.ccxt.GetTradesResponse\x12B\n" +
	"\vHealthCheck\x12\x18.ccxt.HealthCheckRequest\x1a\x19.ccxt.HealthCheckResponseBDZBgithub.com/irfandi/celebrum-ai-go/services/backend-api/pkg/pb/ccxtb\x06proto3"

var (
	file_ccxt_service_proto_rawDescOnce sync.Once
	file_ccxt_service_proto_rawDescData []byte
)

func file_ccxt_service_proto_rawDescGZIP() []byte {
	file_ccxt_service_proto_rawDescOnce.Do(func() {
		file_ccxt_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ccxt_service_proto_rawDesc), len(file_ccxt_service_proto_rawDesc)))
	})
	return file_ccxt_service_proto_rawDescData
}

var file_ccxt_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_ccxt_service_proto_goTypes = []any{
	(*GetTickerRequest)(nil),        // 0: ccxt.GetTickerRequest
	(*GetTickerResponse)(nil),       // 1: ccxt.GetTickerResponse
	(*TickerData)(nil),              // 2: ccxt.TickerData
	(*GetTickersRequest)(nil),       // 3: ccxt.GetTickersRequest
	(*ExchangeTicker)(nil),          // 4: ccxt.ExchangeTicker
	(*GetTickersResponse)(nil),      // 5: ccxt.GetTickersResponse
	(*GetMarketsRequest)(nil),       // 6: ccxt.GetMarketsRequest
	(*GetMarketsResponse)(nil),      // 7: ccxt.GetMarketsResponse
	(*GetFundingRatesRequest)(nil),  // 8: ccxt.GetFundingRatesRequest
	(*GetFundingRatesResponse)(nil), // 9: ccxt.GetFundingRatesResponse
	(*FundingRate)(nil),             // 10: ccxt.FundingRate
	(*GetOrderBookRequest)(nil),     // 11: ccxt.GetOrderBookRequest
	(*GetOrderBookResponse)(nil),    // 12: ccxt.GetOrderBookResponse
	(*OrderBook)(nil),               // 13: ccxt.OrderBook
	(*PriceLevel)(nil),              // 14: ccxt.PriceLevel
	(*GetTradesRequest)(nil),        // 15: ccxt.GetTradesRequest
	(*Trade)(nil),                   // 16: ccxt.Trade
	(*GetTradesResponse)(nil),       // 17: ccxt.GetTradesResponse
	(*GetOHLCVRequest)(nil),         // 18: ccxt.GetOHLCVRequest
	(*GetOHLCVResponse)(nil),        // 19: ccxt.GetOHLCVResponse
	(*OHLCV)(nil),                   // 20: ccxt.OHLCV
	(*GetExchangesRequest)(nil),     // 21: ccxt.GetExchangesRequest
	(*GetExchangesResponse)(nil),    // 22: ccxt.GetExchangesResponse
	(*ExchangeInfo)(nil),            // 23: ccxt.ExchangeInfo
	(*HealthCheckRequest)(nil),      // 24: ccxt.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 25: ccxt.HealthCheckResponse
}
var file_ccxt_service_proto_depIdxs = []int32{
	2,  // 0: ccxt.GetTickerResponse.ticker:type_name -> ccxt.TickerData
	2,  // 1: ccxt.ExchangeTicker.ticker:type_name -> ccxt.TickerData
	4,  // 2: ccxt.GetTickersResponse.tickers:type_name -> ccxt.ExchangeTicker
	10, // 3: ccxt.GetFundingRatesResponse.rates:type_name -> ccxt.FundingRate
	13, // 4: ccxt.GetOrderBookResponse.orderbook:type_name -> ccxt.OrderBook
	14, // 5: ccxt.OrderBook.bids:type_name -> ccxt.PriceLevel
	14, // 6: ccxt.OrderBook.asks:type_name -> ccxt.PriceLevel
	16, // 7: ccxt.GetTradesResponse.trades:type_name -> ccxt.Trade
	20, // 8: ccxt.GetOHLCVResponse.candles:type_name -> ccxt.OHLCV
	23, // 9: ccxt.GetExchangesResponse.exchanges:type_name -> ccxt.ExchangeInfo
	0,  // 10: ccxt.CcxtService.GetTicker:input_type -> ccxt.GetTickerRequest
	6,  // 11: ccxt.CcxtService.GetMarkets:input_type -> ccxt.GetMarketsRequest
	8,  // 12: ccxt.CcxtService.GetFundingRates:input_type -> ccxt.GetFundingRatesRequest
	11, // 13: ccxt.CcxtService.GetOrderBook:input_type -> ccxt.GetOrderBookRequest
	18, // 14: ccxt.CcxtService.GetOHLCV:input_type -> ccxt.GetOHLCVRequest
	21, // 15: ccxt.CcxtService.GetExchanges:input_type -> ccxt.GetExchangesRequest
	3,  // 16: ccxt.CcxtService.GetTickers:input_type -> ccxt.GetTickersRequest
	15, // 17: ccxt.CcxtService.GetTrades:input_type -> ccxt.GetTradesRequest
	24, // 18: ccxt.CcxtService.HealthCheck:input_type -> ccxt.HealthCheckRequest
	1,  // 19: ccxt.CcxtService.GetTicker:output_type -> ccxt.GetTickerResponse
	7,  // 20: ccxt.CcxtService.GetMarkets:output_type -> ccxt.GetMarketsResponse
	9,  // 21: ccxt.CcxtService.GetFundingRates:output_type -> ccxt.GetFundingRatesResponse
	12, // 22: ccxt.CcxtService.GetOrderBook:output_type -> ccxt.GetOrderBookResponse
	19, // 23: ccxt.CcxtService.GetOHLCV:output_type -> ccxt.GetOHLCVResponse
	22, // 24: ccxt.CcxtService.GetExchanges:output_type -> ccxt.GetExchangesResponse
	5,  // 25: ccxt.CcxtService.GetTickers:output_type -> ccxt.GetTickersResponse
	17, // 26: ccxt.CcxtService.GetTrades:output_type -> ccxt.GetTradesResponse
	25, // 27: ccxt.CcxtService.HealthCheck:output_type -> ccxt.HealthCheckResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ccxt_service_proto_init() }
func file_ccxt_service_proto_init() {
	if File_ccxt_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ccxt_service_proto_rawDesc), len(file_ccxt_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ccxt_service_proto_goTypes,
		DependencyIndexes: file_ccxt_service_proto_depIdxs,
		MessageInfos:      file_ccxt_service_proto_msgTypes,
	}.Build()
	File_ccxt_service_proto = out.File
	file_ccxt_service_proto_goTypes = nil
	file_ccxt_service_proto_depIdxs = nil
}
