# Celebrum AI Local Development Configuration
# Copy from config.template.yml with local defaults

# Application environment
environment: development

# Logging configuration
logging:
  level: debug
  format: text
  output: stdout
  file_path: logs/app.log

# Server configuration
server:
  port: 8080
  host: 0.0.0.0
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"

# Database configuration
database:
  host: ${DATABASE_HOST:-postgres}
  port: ${DATABASE_PORT:-5432}
  user: ${DATABASE_USER:-postgres}
  password: ${DATABASE_PASSWORD:?DATABASE_PASSWORD must be set in .env file}
  dbname: ${DATABASE_DBNAME:-celebrum_ai}
  sslmode: ${DATABASE_SSLMODE:-disable}
  max_open_conns: ${DATABASE_MAX_CONNS:-25}
  max_idle_conns: ${DATABASE_MAX_IDLE_CONNS:-5}
  conn_max_lifetime: ${DATABASE_CONN_MAX_LIFETIME:-300s}
  conn_max_idle_time: ${DATABASE_CONN_MAX_IDLE_TIME:-60s}
  # PostgreSQL 18 specific optimizations
  application_name: ${DATABASE_APP_NAME:-celebrum-ai}
  connect_timeout: ${DATABASE_CONNECT_TIMEOUT:-30}
  statement_timeout: ${DATABASE_STATEMENT_TIMEOUT:-300000}
  query_timeout: ${DATABASE_QUERY_TIMEOUT:-300000}
  # Connection pool tuning for async operations
  pool_timeout: ${DATABASE_POOL_TIMEOUT:-10}
  pool_health_check_period: ${DATABASE_HEALTH_CHECK_PERIOD:-30}
  pool_max_lifetime: ${DATABASE_POOL_MAX_LIFETIME:-3600}
  pool_idle_timeout: ${DATABASE_POOL_IDLE_TIMEOUT:-600}
  # Enable PostgreSQL 18 async features
  enable_async: true
  async_batch_size: ${DATABASE_ASYNC_BATCH_SIZE:-1000}
  async_concurrency: ${DATABASE_ASYNC_CONCURRENCY:-10}

# Redis configuration
redis:
  host: ${REDIS_HOST:-redis}
  port: ${REDIS_PORT:-6379}
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s

# CCXT Service configuration
ccxt:
  service_url: ${CCXT_SERVICE_URL:-http://ccxt-service:3001}
  timeout: 30s
  retry_attempts: 3
  retry_delay: 1s
  rate_limit:
    requests_per_second: 10
    burst: 20

# Telegram Bot configuration
telegram:
  bot_token: ""
  webhook_url: ""
  webhook_secret: ""
  timeout: 30s

# Market Data configuration
market_data:
  collection_interval: 30s
  batch_size: 100
  max_retries: 3
  timeout: 15s
  exchanges:
    - binance
    - coinbase
    - kraken
    - bitfinex
    - huobi
    - bybit

# Arbitrage configuration
arbitrage:
  min_profit_threshold: 0.5
  max_trade_amount: 1000.0
  check_interval: 10s

# Technical Analysis configuration
technical_analysis:
  indicators:
    - RSI
    - MACD
    - SMA
    - EMA
    - BOLLINGER_BANDS
  timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
  calculation_interval: 60s

# Security configuration
security:
  jwt_secret: ${JWT_SECRET:-dev-jwt-secret-change-this-in-production}
  jwt_expiry: 24h
  bcrypt_cost: 12
  rate_limit:
    requests_per_minute: 100
    burst: 200

# Monitoring configuration
monitoring:
  metrics_enabled: true
  metrics_port: 9090
  health_check_interval: 30s
  prometheus:
    enabled: true
    path: /metrics

# Feature flags
features:
  telegram_bot: true
  web_interface: true
  api_v1: true
  real_trading: false
  paper_trading: true

# External APIs
external_apis:
  coingecko:
    base_url: https://api.coingecko.com/api/v3
    timeout: 10s
    rate_limit: 50
  coinmarketcap:
    base_url: https://pro-api.coinmarketcap.com/v1
    api_key: ""
    timeout: 10s
    rate_limit: 333
