# Celebrum AI Production Configuration
# Optimized for Digital Ocean deployment

# Application environment
environment: production

# Logging configuration
logging:
  level: info
  format: json
  output: stdout

# Server configuration
server:
  port: 8080
  host: 0.0.0.0
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  allowed_origins:
    - "https://celebrum-ai.com"
    - "https://www.celebrum-ai.com"
    - "https://api.celebrum-ai.com"

# Database configuration (Digital Ocean Managed Database)
database:
  # Use DATABASE_URL environment variable for connection
  # This should be set in your Digital Ocean App Platform environment
  database_url: "${DATABASE_URL}"
  
  # SSL is required for Digital Ocean managed databases
  sslmode: require
  
  # Connection pool settings optimized for cloud deployment
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: 600s
  conn_max_idle_time: 300s

# Redis configuration (Digital Ocean Managed Redis)
redis:
  # Use REDIS_URL if available, otherwise individual settings
  host: "${REDIS_HOST:localhost}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  
  # Connection pool settings
  pool_size: 20
  min_idle_conns: 5
  dial_timeout: 10s
  read_timeout: 5s
  write_timeout: 5s
  pool_timeout: 10s
  idle_timeout: 600s

# CCXT Service configuration
ccxt:
  service_url: "${CCXT_SERVICE_URL:http://localhost:3001}"
  timeout: 30s
  retry_attempts: 5
  retry_delay: 2s
  rate_limit:
    requests_per_second: 20
    burst: 50

# Telegram Bot configuration
telegram:
  bot_token: "${TELEGRAM_BOT_TOKEN}"
  webhook_url: "${TELEGRAM_WEBHOOK_URL}"
  webhook_secret: "${TELEGRAM_WEBHOOK_SECRET}"
  timeout: 30s

# Market Data configuration
market_data:
  collection_interval: 15s
  batch_size: 200
  max_retries: 5
  timeout: 30s
  exchanges:
    - binance
    - coinbase
    - kraken
    - bybit
    - okx

# Arbitrage configuration
arbitrage:
  min_profit_threshold: 0.3
  max_trade_amount: 10000.0
  check_interval: 5s
  enabled_pairs:
    - BTC/USDT
    - ETH/USDT
    - BNB/USDT
    - ADA/USDT
    - SOL/USDT
    - DOT/USDT
    - LINK/USDT
    - AVAX/USDT
    - MATIC/USDT
    - ATOM/USDT

# Technical Analysis configuration
technical_analysis:
  indicators:
    - RSI
    - MACD
    - SMA
    - EMA
    - BOLLINGER_BANDS
  timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
  calculation_interval: 30s

# Security configuration
security:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiry: 24h
  bcrypt_cost: 14
  rate_limit:
    requests_per_minute: 200
    burst: 500

# Monitoring configuration
monitoring:
  metrics_enabled: true
  metrics_port: 9090
  health_check_interval: 15s
  prometheus:
    enabled: true
    path: /metrics

# Feature flags
features:
  telegram_bot: true
  web_interface: true
  api_v1: true
  real_trading: false
  paper_trading: true

# External APIs
external_apis:
  coingecko:
    base_url: https://api.coingecko.com/api/v3
    timeout: 15s
    rate_limit: 100
  coinmarketcap:
    base_url: https://pro-api.coinmarketcap.com/v1
    api_key: "${COINMARKETCAP_API_KEY}"
    timeout: 15s
    rate_limit: 1000