# Celebrum AI CI/CD Configuration
# Optimized for CI/CD environments

# Application environment
environment: testing

# Logging configuration
logging:
  level: info
  format: json
  output: stdout

# Server configuration
server:
  port: 8080
  host: 0.0.0.0
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  allowed_origins:
    - "http://localhost:8080"

# Database configuration
database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: celebrum_ai
  sslmode: disable
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 60s
  conn_max_idle_time: 30s

# Redis configuration
redis:
  host: redis
  port: 6379
  password: ""
  db: 0
  pool_size: 5
  min_idle_conns: 2
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 60s

# CCXT Service configuration
ccxt:
  service_url: http://ccxt-service:8081
  timeout: 30s
  retry_attempts: 2
  retry_delay: 500ms
  rate_limit:
    requests_per_second: 5
    burst: 10

# Telegram Bot configuration
telegram:
  bot_token: "${BOT_TOKEN}"
  webhook_url: "http://localhost:8080/api/v1/telegram/webhook"
  webhook_secret: "${WEBHOOK_SECRET}"
  timeout: 30s

# Market Data configuration
market_data:
  collection_interval: 60s
  batch_size: 50
  max_retries: 2
  timeout: 10s
  exchanges:
    - binance
    - coinbase

# Arbitrage configuration
arbitrage:
  min_profit_threshold: 1.0
  max_trade_amount: 100.0
  check_interval: 30s

# Technical Analysis configuration
technical_analysis:
  indicators:
    - RSI
    - MACD
  timeframes:
    - 5m
    - 1h
  calculation_interval: 60s

# Security configuration
security:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiry: 1h
  bcrypt_cost: 10
  rate_limit:
    requests_per_minute: 50
    burst: 100

# Monitoring configuration
monitoring:
  metrics_enabled: true
  metrics_port: 9090
  health_check_interval: 30s
  prometheus:
    enabled: true
    path: /metrics

# Feature flags
features:
  telegram_bot: true
  web_interface: true
  api_v1: true
  real_trading: false
  paper_trading: true

# External APIs
external_apis:
  coingecko:
    base_url: https://api.coingecko.com/api/v3
    timeout: 5s
    rate_limit: 10
  coinmarketcap:
    base_url: https://pro-api.coinmarketcap.com/v1
    api_key: ""
    timeout: 5s
    rate_limit: 10
