# Celebrum AI Configuration Template
# This template file should be used with environment variable substitution
# Use config.local.yml for local development, config.prod.yml for production

# Application environment (development, staging, production)
environment: ${ENVIRONMENT:-development}

# Logging configuration
logging:
  level: ${LOG_LEVEL:-info}  # debug, info, warn, error
  format: ${LOG_FORMAT:-json}  # json, text
  output: ${LOG_OUTPUT:-stdout}  # stdout, file
  file_path: ${LOG_FILE_PATH:-logs/app.log}

# Server configuration
server:
  port: ${SERVER_PORT:-8080}
  host: ${SERVER_HOST:-0.0.0.0}
  read_timeout: ${SERVER_READ_TIMEOUT:-30s}
  write_timeout: ${SERVER_WRITE_TIMEOUT:-30s}
  idle_timeout: ${SERVER_IDLE_TIMEOUT:-60s}
  allowed_origins: ${SERVER_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:8080}

# Database configuration
# Supports both individual settings and DATABASE_URL
# DATABASE_URL takes precedence if provided
database:
  host: ${DATABASE_HOST:-localhost}
  port: ${DATABASE_PORT:-5432}
  user: ${DATABASE_USER:-postgres}
  password: ${DATABASE_PASSWORD:?DATABASE_PASSWORD must be set in .env file}
  dbname: ${DATABASE_DBNAME:-celebrum_ai}
  sslmode: ${DATABASE_SSLMODE:-disable}
  database_url: ${DATABASE_URL:-}
  # Connection pool settings
  max_open_conns: ${DATABASE_MAX_OPEN_CONNS:-25}
  max_idle_conns: ${DATABASE_MAX_IDLE_CONNS:-5}
  conn_max_lifetime: ${DATABASE_CONN_MAX_LIFETIME:-300s}
  conn_max_idle_time: ${DATABASE_CONN_MAX_IDLE_TIME:-60s}

# Redis configuration
redis:
  host: ${REDIS_HOST:-localhost}
  port: ${REDIS_PORT:-6379}
  password: ${REDIS_PASSWORD:-}
  db: ${REDIS_DB:-0}
  pool_size: ${REDIS_POOL_SIZE:-10}
  min_idle_conns: ${REDIS_MIN_IDLE_CONNS:-5}
  dial_timeout: ${REDIS_DIAL_TIMEOUT:-5s}
  read_timeout: ${REDIS_READ_TIMEOUT:-3s}
  write_timeout: ${REDIS_WRITE_TIMEOUT:-3s}
  pool_timeout: ${REDIS_POOL_TIMEOUT:-4s}
  idle_timeout: ${REDIS_IDLE_TIMEOUT:-300s}

# CCXT Service configuration
ccxt:
  service_url: ${CCXT_SERVICE_URL:-http://localhost:8081}
  timeout: ${CCXT_TIMEOUT:-30}
  retry_attempts: ${CCXT_RETRY_ATTEMPTS:-3}
  retry_delay: ${CCXT_RETRY_DELAY:-1s}
  rate_limit:
    requests_per_second: ${CCXT_RATE_LIMIT_RPS:-10}
    burst: ${CCXT_RATE_LIMIT_BURST:-20}

# Telegram Bot configuration
telegram:
  bot_token: ${TELEGRAM_BOT_TOKEN:-}
  webhook_url: ${TELEGRAM_WEBHOOK_URL:-}
  webhook_secret: ${TELEGRAM_WEBHOOK_SECRET:-}
  timeout: ${TELEGRAM_TIMEOUT:-30s}

# Market Data configuration
market_data:
  collection_interval: ${MARKET_DATA_COLLECTION_INTERVAL:-90s}
  batch_size: ${MARKET_DATA_BATCH_SIZE:-500}
  max_retries: ${MARKET_DATA_MAX_RETRIES:-3}
  timeout: ${MARKET_DATA_TIMEOUT:-15s}
  exchanges: ${MARKET_DATA_EXCHANGES:-binance,coinbase,kraken,bitfinex,huobi,bybit}

# Arbitrage configuration
arbitrage:
  min_profit_threshold: ${ARBITRAGE_MIN_PROFIT_THRESHOLD:-0.5}
  max_trade_amount: ${ARBITRAGE_MAX_TRADE_AMOUNT:-1000.0}
  check_interval: ${ARBITRAGE_CHECK_INTERVAL:-2m}

# Technical Analysis configuration
technical_analysis:
  indicators: ${TECHNICAL_ANALYSIS_INDICATORS:-RSI,MACD,SMA,EMA,BOLLINGER_BANDS}
  timeframes: ${TECHNICAL_ANALYSIS_TIMEFRAMES:-1m,5m,15m,1h,4h,1d}
  calculation_interval: ${TECHNICAL_ANALYSIS_CALCULATION_INTERVAL:-60s}

# Security configuration
security:
  jwt_secret: ${JWT_SECRET:-}
  jwt_expiry: ${JWT_EXPIRY:-24h}
  bcrypt_cost: ${BCRYPT_COST:-12}
  rate_limit:
    requests_per_minute: ${SECURITY_RATE_LIMIT_RPM:-100}
    burst: ${SECURITY_RATE_LIMIT_BURST:-200}

# Monitoring configuration
monitoring:
  metrics_enabled: ${METRICS_ENABLED:-true}
  metrics_port: ${METRICS_PORT:-9090}
  health_check_interval: ${HEALTH_CHECK_INTERVAL:-30s}
  prometheus:
    enabled: ${PROMETHEUS_ENABLED:-true}
    path: ${PROMETHEUS_PATH:-/metrics}

# Feature flags
features:
  telegram_bot: ${FEATURE_TELEGRAM_BOT:-true}
  web_interface: ${FEATURE_WEB_INTERFACE:-true}
  api_v1: ${FEATURE_API_V1:-true}
  real_trading: ${FEATURE_REAL_TRADING:-false}
  paper_trading: ${FEATURE_PAPER_TRADING:-true}

# External APIs
external_apis:
  coingecko:
    base_url: ${COINGECKO_BASE_URL:-https://api.coingecko.com/api/v3}
    timeout: ${COINGECKO_TIMEOUT:-10s}
    rate_limit: ${COINGECKO_RATE_LIMIT:-50}
  coinmarketcap:
    base_url: ${COINMARKETCAP_BASE_URL:-https://pro-api.coinmarketcap.com/v1}
    api_key: ${COINMARKETCAP_API_KEY:-}
    timeout: ${COINMARKETCAP_TIMEOUT:-10s}
    rate_limit: ${COINMARKETCAP_RATE_LIMIT:-333}
