# Production Configuration
# This file contains production-specific settings

environment: production

# Logging configuration
logging:
  level: info
  format: json
  output: file
  file: /app/logs/celebrum-ai.log
  max_size: 100MB
  max_backups: 5
  max_age: 30

# Server configuration
server:
  port: 8080
  host: 0.0.0.0
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  graceful_shutdown: 30s

# Database configuration
database:
  host: postgres
  port: 5432
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  dbname: ${DATABASE_DBNAME}
  sslmode: require
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m
  conn_max_idle_time: 5m

# Redis configuration
redis:
  host: redis
  port: 6379
  password: ${REDIS_PASSWORD}
  db: 0
  max_retries: 3
  pool_size: 10
  min_idle_conns: 5
  max_conn_age: 1h
  idle_timeout: 5m

# CCXT service configuration
ccxt:
  service_url: http://ccxt-service:3001
  timeout: 30s
  max_retries: 3
  rate_limit: 100

# Telegram bot configuration
telegram:
  bot_token: ${TELEGRAM_BOT_TOKEN}
  webhook_url: ${TELEGRAM_WEBHOOK_URL}
  webhook_secret: ${TELEGRAM_WEBHOOK_SECRET}
  max_connections: 40

# Market data configuration
market_data:
  update_interval: 30s
  cache_ttl: 5m
  max_symbols: 1000
  exchanges:
    - binance
    - coinbase
    - kraken
    - bitfinex

# Arbitrage configuration
arbitrage:
  enabled: true
  min_profit_threshold: 0.005
  max_position_size: 1000
  risk_limit: 0.02
  check_interval: 5s

# Technical analysis configuration
technical_analysis:
  enabled: true
  indicators:
    - rsi
    - macd
    - bollinger_bands
    - moving_averages
  update_interval: 1m
  cache_ttl: 15m

# Security configuration
security:
  jwt_secret: ${JWT_SECRET}
  jwt_expiry: 24h
  cors_origins:
    - https://celebrum-ai.com
    - https://app.celebrum-ai.com
  rate_limit: 100
  rate_limit_window: 1m

# Monitoring configuration
monitoring:
  metrics_enabled: true
  metrics_port: 9090
  metrics_path: /metrics
  health_check_port: 8080
  health_check_path: /health
  prometheus_enabled: true
  jaeger_enabled: false

# Feature flags
features:
  arbitrage_bot: true
  technical_analysis: true
  paper_trading: false
  real_trading: false
  notifications: true
  webhooks: true

# External APIs
external_apis:
  coinmarketcap:
    api_key: ${COINMARKETCAP_API_KEY}
    base_url: https://pro-api.coinmarketcap.com
    timeout: 10s
  coingecko:
    base_url: https://api.coingecko.com/api/v3
    timeout: 10s