receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"
  
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_binary:
        endpoint: 0.0.0.0:6832
  
  zipkin:
    endpoint: 0.0.0.0:9411
  
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']
        - job_name: 'celebrum-ai-go'
          scrape_interval: 15s
          static_configs:
            - targets: ['host.docker.internal:8080']
        - job_name: 'ccxt-service'
          scrape_interval: 15s
          static_configs:
            - targets: ['host.docker.internal:3001']

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  
  memory_limiter:
    limit_mib: 1000
    spike_limit_mib: 200
    check_interval: 5s
  
  resource:
    attributes:
      - key: deployment.environment
        value: "development"
        action: upsert
      - key: service.namespace
        value: "celebrum-ai"
        action: upsert
  
  attributes:
    actions:
      - key: http.user_agent
        action: delete
      - key: http.request.header.authorization
        action: delete
      - key: db.statement
        action: update
        from_attribute: db.statement
        to_attribute: db.operation
  
  span:
    name:
      to_attributes:
        rules:
          - ^/api/v1/(?P<version>.*?)/(?P<operation>.*?)$
      from_attributes: ["http.route"]
  
  filter:
    traces:
      span:
        - 'attributes["http.route"] == "/health"'
        - 'attributes["http.route"] == "/metrics"'

exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s&compress=lz4
    database: signoz_traces
    traces_table_name: signoz_traces
    operations_table_name: signoz_operations
    index_table_name: signoz_index_v2
    spans_table_name: signoz_spans
    attribute_table_name: signoz_attribute_keys
    resource_table_name: signoz_resource_keys
    encoding: json
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200
  
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      cluster: "celebrum-ai-cluster"

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: 0.0.0.0:1777
  
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [memory_limiter, resource, attributes, span, filter, batch]
      exporters: [clickhouse, logging]
    
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, logging]
  
  telemetry:
    logs:
      level: "debug"
    metrics:
      address: 0.0.0.0:8888
      level: detailed