global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'celebrum-ai-cluster'
    environment: 'development'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'signoz-query-service'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 15s
    metrics_path: '/api/v1/metrics'

  - job_name: 'signoz-otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 15s

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'celebrum-ai-go'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  - job_name: 'ccxt-service'
    static_configs:
      - targets: ['host.docker.internal:3001']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['194.233.73.250:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093