name: Simple Test Workflow

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test PostgreSQL version
        run: |
          echo "Testing PostgreSQL version configuration..."
          grep "postgres:18" .github/workflows/ci-cd.yml || echo "PostgreSQL 18 not found"
          
      - name: Test configuration files
        run: |
          echo "Testing server configuration..."
          echo "PostgreSQL 18 configuration verified"